name: easy_pong
description: "Classic Pong fun reimagined with local multiplayer and modern themes."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: 3.32.6

dependencies:
  flame: ^1.30.1
  flame_audio: ^2.11.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  window_manager: ^0.5.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/pixel_football_field.jpg
    - assets/audio/ping.mp3

  fonts:
    - family: AtariClassic
      fonts:
        - asset: assets/fonts/AtariClassic.ttf