name: easy_pong
description: "Over Engineered Pong Game Made Using Flutter and Flame."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flame: ^1.18.0
  flame_audio: ^2.10.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/pixel_football_field.jpg
    - assets/audio/ping.mp3

  fonts:
    - family: AtariClassic
      fonts:
        - asset: assets/fonts/AtariClassic.ttf