icon: snap/gui/easy-pong.png
summary: An Over Engineered Pong Game
group: Applications/Utility
vendor: adeeteya
packager: Aditya R
packagerEmail: adeeteya@gmail.com
license: MIT
url: https://github.com/adeeteya/EasyPong

display_name: Easy Pong

keywords:
  - Pong
  - Game

generic_name: Easy Pong
categories:
  - Games

startup_notify: true