// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJkdNcCXEtTJA7rTWWxaeSJRCmkh0V00o',
    appId: '1:436275011199:web:a6e95679e5197df462294a',
    messagingSenderId: '436275011199',
    projectId: 'easy-pong-35665',
    authDomain: 'easy-pong-35665.firebaseapp.com',
    databaseURL: 'https://easy-pong-35665-default-rtdb.firebaseio.com',
    storageBucket: 'easy-pong-35665.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZZuvKW1zk18Mu8DjyXVxEoVbDrLY_hOY',
    appId: '1:436275011199:android:a1f019a5da19b59262294a',
    messagingSenderId: '436275011199',
    projectId: 'easy-pong-35665',
    databaseURL: 'https://easy-pong-35665-default-rtdb.firebaseio.com',
    storageBucket: 'easy-pong-35665.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-cT6OKphc-5hlPu8KqHyzKIvZYJIXvEY',
    appId: '1:436275011199:ios:66b98ec9292a71ea62294a',
    messagingSenderId: '436275011199',
    projectId: 'easy-pong-35665',
    databaseURL: 'https://easy-pong-35665-default-rtdb.firebaseio.com',
    storageBucket: 'easy-pong-35665.firebasestorage.app',
    iosBundleId: 'com.adeeteya.easyPong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-cT6OKphc-5hlPu8KqHyzKIvZYJIXvEY',
    appId: '1:436275011199:ios:66b98ec9292a71ea62294a',
    messagingSenderId: '436275011199',
    projectId: 'easy-pong-35665',
    databaseURL: 'https://easy-pong-35665-default-rtdb.firebaseio.com',
    storageBucket: 'easy-pong-35665.firebasestorage.app',
    iosBundleId: 'com.adeeteya.easyPong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJkdNcCXEtTJA7rTWWxaeSJRCmkh0V00o',
    appId: '1:436275011199:web:422fb4c406a14f7b62294a',
    messagingSenderId: '436275011199',
    projectId: 'easy-pong-35665',
    authDomain: 'easy-pong-35665.firebaseapp.com',
    databaseURL: 'https://easy-pong-35665-default-rtdb.firebaseio.com',
    storageBucket: 'easy-pong-35665.firebasestorage.app',
  );

}