display_name: Easy Pong
package_name: easy-pong
maintainer:
  name: Aditya
  email: adeeteya@gmail.com
priority: optional
section: x11
installed_size: 9280
essential: false
icon: snap/gui/easy-pong.png

postinstall_scripts:
  - echo "Thanks for installing Easy Pong. If you like the app please give it a star on GitHub"
postuninstall_scripts:
  - echo "Sorry to see you go. If there are problems in the app please open an issue on GitHub"

keywords:
  - Pong
  - Game

generic_name: Easy Pong

categories:
  - Game

startup_notify: true